#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format
#
# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md
echo -n "weather "; stat -c '%a' weather
echo -n "Readme.md "; stat -c '%a' ../README.md



