#!/usr/bin/env bash

# Removes all files written in .gitignore of any git repository (multiple) present inside current directory
# To find list of all git repos inside current directory you can use: "find . -name .git -type d -prune"
for d in */ ; do 
    if [ -f "$d/.gitignore" ]; then 
        while read -r line; do 
            rm -f "$d/$line" 
        done < "$d/.gitignore" 
    fi 
done