#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this

# run the basic command to fetch ssid

echo "The currently connected wifi SSID"
iw dev wlan0 link | grep -w "SSID"

# if this command fails, (exit code != 0) 
# I noticed the command not working for my fedora, thus a slight modification i introduced

if [ $? != 0 ]
then
    clear
    echo "The currently connected wifi SSID"
    iw dev wlp3s0 link | grep -w "SSID"
fi
